# -*- coding: utf-8 -*-
"""network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCNSWgB4rg_c4FKXe3PjKCgJBX9kQHrI
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Model


class StochasticDepth(layers.Layer):
    def __init__(self, drop_prob: float = 0.0, **kwargs):
        super().__init__(**kwargs)
        self.drop_prob = float(drop_prob)

    def call(self, x, training=False):
        if (not training) or self.drop_prob == 0.0:
            return x
        keep_prob = 1.0 - self.drop_prob
        shape = (tf.shape(x)[0],) + (1,) * (len(x.shape) - 1)
        random_tensor = keep_prob + tf.random.uniform(shape, 0, 1)
        binary_mask = tf.floor(random_tensor)
        return (x / keep_prob) * binary_mask


class PositionEmbedding(layers.Layer):
    def __init__(self, initializer="glorot_uniform", **kwargs):
        super().__init__(**kwargs)
        self.initializer = keras.initializers.get(initializer)
        self.pos_emb = None

    def build(self, input_shape):
        seq_len = int(input_shape[1])
        embed_dim = int(input_shape[2])
        self.pos_emb = self.add_weight(
            name="pos_emb",
            shape=(seq_len, embed_dim),
            initializer=self.initializer,
            trainable=True,
        )
        super().build(input_shape)

    def call(self, token_embeddings):
        return token_embeddings + tf.expand_dims(self.pos_emb, axis=0)


class SequencePooling(layers.Layer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.attn_score = layers.Dense(1)

    def call(self, token_embeddings):
        attn_weights = tf.nn.softmax(self.attn_score(token_embeddings), axis=1)
        attn_weights = tf.transpose(attn_weights, perm=(0, 2, 1))
        pooled = tf.matmul(attn_weights, token_embeddings)
        return tf.squeeze(pooled, axis=1)

class TransformerEncoderBlock(layers.Layer):
    def __init__(self, embed_dim: int = 128, num_heads: int = 4, dropout: float = 0.1, sd_rate: float = 0.1, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = int(embed_dim)
        self.num_heads = int(num_heads)
        self.dropout = float(dropout)
        self.sd_rate = float(sd_rate)

        self.key_dim = max(1, self.embed_dim // self.num_heads)

        self.ln1 = layers.LayerNormalization(epsilon=1e-6)
        self.mhsa = layers.MultiHeadAttention(
            num_heads=self.num_heads,
            key_dim=self.key_dim,
            dropout=self.dropout,
        )
        self.drop1 = layers.Dropout(self.dropout)
        self.sd1 = StochasticDepth(self.sd_rate)
        self.add1 = layers.Add()

        self.ln2 = layers.LayerNormalization(epsilon=1e-6)
        # FFN dim = 128 (same as embed_dim) to match Table-2
        self.ffn1 = layers.Dense(self.embed_dim, activation="gelu")
        self.ffn2 = layers.Dense(self.embed_dim)
        self.drop2 = layers.Dropout(self.dropout)
        self.sd2 = StochasticDepth(self.sd_rate)
        self.add2 = layers.Add()

    def call(self, x, training=False):
        h = self.ln1(x)
        h = self.mhsa(h, h, training=training)
        h = self.drop1(h, training=training)
        h = self.sd1(h, training=training)
        x = self.add1([x, h])

        h = self.ln2(x)
        h = self.ffn1(h)
        h = self.ffn2(h)
        h = self.drop2(h, training=training)
        h = self.sd2(h, training=training)
        x = self.add2([x, h])
        return x

class CCTTokenizer(layers.Layer):
    def __init__(
        self,
        conv_layers=2,
        num_output_channels=(64, 128),
        kernel_size=3,
        stride=1,
        padding=1,
        pooling_kernel_size=3,
        pooling_stride=2,
        l2_reg=1e-4,
        **kwargs
    ):
        super().__init__(**kwargs)
        self.conv_layers = int(conv_layers)
        self.num_output_channels = tuple(int(c) for c in num_output_channels)
        self.kernel_size = int(kernel_size)
        self.stride = int(stride)
        self.padding = int(padding)
        self.pooling_kernel_size = int(pooling_kernel_size)
        self.pooling_stride = int(pooling_stride)
        self.l2_reg = float(l2_reg)

        self.conv_model = keras.Sequential(name="cct_tokenizer")
        for i in range(self.conv_layers):
            self.conv_model.add(
                layers.Conv2D(
                    self.num_output_channels[i],
                    kernel_size=self.kernel_size,
                    strides=self.stride,
                    padding="valid",
                    use_bias=False,
                    activation="relu",
                    kernel_initializer="he_normal",
                    kernel_regularizer=keras.regularizers.l2(self.l2_reg),
                    name=f"tok_conv_{i}",
                )
            )
            self.conv_model.add(layers.ZeroPadding2D(self.padding, name=f"tok_pad_{i}"))
            self.conv_model.add(
                layers.MaxPooling2D(
                    pool_size=self.pooling_kernel_size,
                    strides=self.pooling_stride,
                    padding="same",
                    name=f"tok_pool_{i}",
                )
            )

    def call(self, images, training=False):
        x = self.conv_model(images, training=training)
        b = tf.shape(x)[0]
        h = tf.shape(x)[1]
        w = tf.shape(x)[2]
        c = tf.shape(x)[3]
        return tf.reshape(x, (b, h * w, c))

class MultiLevelAttentionUnit(layers.Layer):
    def __init__(self, reduction=8, init_alpha=0.5, **kwargs):
        super().__init__(**kwargs)
        self.reduction = int(reduction)
        self.init_alpha = float(init_alpha)

        self.alpha = None
        self.pa_conv = None
        self.sa_conv = layers.Conv2D(1, kernel_size=7, padding="same", activation="sigmoid", name="sa_conv")
        self.se_dense1 = None
        self.se_dense2 = None
        self.fuse_conv = None

        self.gap_keep = layers.GlobalAveragePooling2D(keepdims=True)
        self.concat = layers.Concatenate(axis=-1)
        self.mul = layers.Multiply()

    def build(self, input_shape):
        channels = int(input_shape[-1])
        hidden = max(1, channels // self.reduction)

        self.alpha = self.add_weight(
            name="alpha",
            shape=(),
            initializer=keras.initializers.Constant(self.init_alpha),
            trainable=True,
        )

        self.pa_conv = layers.Conv2D(channels, kernel_size=1, padding="same", activation="sigmoid", name="pa_conv")
        self.se_dense1 = layers.Dense(hidden, activation="relu", name="se_fc1")
        self.se_dense2 = layers.Dense(channels, activation="sigmoid", name="se_fc2")
        self.fuse_conv = layers.Conv2D(channels, kernel_size=1, padding="same", name="fuse_conv")
        super().build(input_shape)

    def call(self, x, training=False):
        pa = self.pa_conv(x)
        f_pa = self.mul([x, pa])

        avg_map = tf.reduce_mean(x, axis=-1, keepdims=True)
        max_map = tf.reduce_max(x, axis=-1, keepdims=True)
        sa_in = self.concat([avg_map, max_map])
        sa = self.sa_conv(sa_in)
        f_sa = self.mul([x, sa])

        se = self.gap_keep(x)
        se = self.se_dense1(se)
        se = self.se_dense2(se)
        f_se = self.mul([x, se])

        combined = tf.add_n([f_pa, f_sa, f_se])
        combined = self.fuse_conv(combined)

        return combined * self.alpha + x * (1.0 - self.alpha)

class SharedStem(layers.Layer):
    def __init__(self, l2_reg=1e-4, **kwargs):
        super().__init__(**kwargs)
        self.l2_reg = float(l2_reg)
        reg = keras.regularizers.l2(self.l2_reg)

        self.conv1 = layers.Conv2D(64, 7, strides=2, padding="same", use_bias=False,
                                   kernel_regularizer=reg, name="stem_conv1")
        self.bn1 = layers.BatchNormalization(name="stem_bn1")
        self.act1 = layers.Activation("relu", name="stem_relu1")

        self.conv2 = layers.Conv2D(128, 3, padding="same", use_bias=False,
                                   kernel_regularizer=reg, name="stem_conv2")
        self.bn2 = layers.BatchNormalization(name="stem_bn2")
        self.act2 = layers.Activation("relu", name="stem_relu2")

        self.conv3 = layers.Conv2D(256, 3, padding="same", use_bias=False,
                                   kernel_regularizer=reg, name="stem_conv3")
        self.bn3 = layers.BatchNormalization(name="stem_bn3")
        self.act3 = layers.Activation("relu", name="stem_relu3")
        self.pool3 = layers.MaxPooling2D(pool_size=2, strides=2, name="stem_pool3")

    def call(self, inputs, training=False):
        x = self.conv1(inputs)
        x = self.bn1(x, training=training)
        x = self.act1(x)

        mid = self.conv2(x)
        mid = self.bn2(mid, training=training)
        mid = self.act2(mid)

        deep = self.conv3(mid)
        deep = self.bn3(deep, training=training)
        deep = self.act3(deep)
        deep = self.pool3(deep)
        return mid, deep

class AlzCCTNet(Model):
    def __init__(
        self,
        input_shape=(128, 128, 3),
        num_classes=3,
        positional_emb=True,
        conv_layers=2,
        tokenizer_channels=(64, 128),
        transformer_layers=4,
        embed_dim=128,
        num_heads=4,
        dropout=0.10,
        sd_rate=0.10,
        mlp_dropout=0.20,
        l2_reg=1e-4,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.num_classes = int(num_classes)
        self.positional_emb = bool(positional_emb)
        reg = keras.regularizers.l2(float(l2_reg))

        self.stem = SharedStem(l2_reg=l2_reg, name="shared_stem")

        self.mla = MultiLevelAttentionUnit(name="mla_unit")
        self.mla_gap = layers.GlobalAveragePooling2D(name="mla_gap")

        self.tokenizer = CCTTokenizer(
            conv_layers=conv_layers,
            num_output_channels=tokenizer_channels,
            l2_reg=l2_reg,
            name="cct_tokenizer",
        )
        self.pos_emb_layer = PositionEmbedding(name="pos_emb") if self.positional_emb else None

        self.transformer_stack = [
            TransformerEncoderBlock(embed_dim=embed_dim, num_heads=num_heads, dropout=dropout, sd_rate=sd_rate, name=f"tx_{i}")
            for i in range(int(transformer_layers))
        ]
        self.seq_pool = SequencePooling(name="seq_pool")

        self.fuse = layers.Concatenate(name="feature_concat")
        self.fc1 = layers.Dense(256, activation="relu", kernel_regularizer=reg, name="head_fc1")
        self.drop1 = layers.Dropout(mlp_dropout, name="head_drop1")
        self.fc2 = layers.Dense(128, activation="relu", kernel_regularizer=reg, name="head_fc2")
        self.drop2 = layers.Dropout(mlp_dropout, name="head_drop2")
        self.out = layers.Dense(self.num_classes, activation="softmax", name="classifier")

    def call(self, images, training=False):
        mid_feat, deep_feat = self.stem(images, training=training)

        mla_feat = self.mla(mid_feat, training=training)
        f_mla = self.mla_gap(mla_feat)

        tokens = self.tokenizer(deep_feat, training=training)
        if self.pos_emb_layer is not None:
            tokens = self.pos_emb_layer(tokens)

        for blk in self.transformer_stack:
            tokens = blk(tokens, training=training)

        f_cct = self.seq_pool(tokens)

        fused = self.fuse([f_cct, f_mla])
        x = self.fc1(fused)
        x = self.drop1(x, training=training)
        x = self.fc2(x)
        x = self.drop2(x, training=training)
        return self.out(x)